# Generated by Django 5.2.8 on 2025-11-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=50)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('contact_number', models.CharField(default='Not Provided', max_length=15)),
                ('address', models.CharField(default='Unknown Address', max_length=200)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
